version: '2'
services:
  ml-predictor:
    image: node:6.5.0
    network_mode: host
    environment:
      - PG_HOST=localhost
    volumes:
      - .:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && npm install && sleep 3 && ./server.js\""
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    network_mode: host
    env_file: development.env
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
  redis:
    image: redis:alpine
    network_mode: host
    ports:
      - "6379:6379"
